name: deploy-server

on:
  push:
    branches: [ server ]
  pull_request:
    branches: [ server ]

jobs:
  deploy:
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Deploy server
      run: |
        pwd
        ls
        cd server
        docker-compose build
        docker-compose up --force-recreate -d
